Added options '-l'. Update options '-u' and '-i' for install images.

diff --git a/sam b/sam
--- a/sam
+++ b/sam
@@ -1,6 +1,13 @@
 #!/bin/bash
 
-DOCKER_PATH="/usr/bin/docker";
+if [[ -z $DOCKER_PATH ]];then
+        DOCKER_PATH='/usr/bin/docker';
+fi;
+
+if [[ -z $SAM_DB_LIST ]];then
+        SAM_DB_LIST='/var/db/sam/list_installed';
+fi;
+
 IMAGE='';
 
 #set -xv
@@ -10,10 +17,10 @@ IMAGE='';
 copy_meta_func () {
 	# input: $IMAGE $DOCKER_PATH
 	TEMPLATE_DIR=`mktemp -d`;
-	$DOCKER_PATH run -i -t --rm -v $TEMPLATE_DIR:$TEMPLATE_DIR  --net=host --entrypoint="cp"  $IMAGE -r /meta $TEMPLATE_DIR/meta 2>&1 > /dev/null;
+	$DOCKER_PATH run -i -t --rm -v $TEMPLATE_DIR:$TEMPLATE_DIR  --net=host --entrypoint="cp" $IMAGE -r /meta $TEMPLATE_DIR/meta 2>&1 > /dev/null;
 	if [[ $? -ne 0 ]]; then
         	echo -e "\E[31mERROR: Directory '/meta' not fount to image.">&2;tput sgr0;
-		rm -rf $TEMPLATE_DIR
+		rm -rf $TEMPLATE_DIR;
 		exit 1;
 	fi;
 	# output $pwd $TEMPLATE_DIR
@@ -26,7 +33,7 @@ uninstall_image_func () {
 	copy_meta_func;
 	pwd=$PWD;
 	cd $TEMPLATE_DIR/meta;
-        source uninstall;
+        source $TEMPLATE_DIR/meta/uninstall;
 	cd $pwd;
         rm -rf $TEMPLATE_DIR;
 	echo;
@@ -36,19 +43,6 @@ uninstall_image_func () {
 install_image_func () {
 	echo;
 	echo -e "\E[32mInstall image $IMAGE";tput sgr0;
-	# Exist installed image
-	OLD_IMAGE=`echo $IMAGE | awk -F ':' 'NF--' | sed 's/ /:/g'`
-	TEST_CONTAINER=`$DOCKER_PATH ps -a | grep $OLD_IMAGE`;	
-	if [[ -n $TEST_CONTAINER ]]; then
-		echo -e "\E[31mERROR: In system installed old version of image..">&2;tput sgr0;
-		echo;
-		echo "    Installed image:";
-		echo;
-	        $DOCKER_PATH ps -a | grep --color=always $OLD_IMAGE;
-		echo;
-		exit 1;
-	fi;
-	
 	copy_meta_func;
 	pwd=$PWD;
         cd $TEMPLATE_DIR/meta;
@@ -59,46 +53,44 @@ install_image_func () {
 	echo;	
 }
 
-# Remove old image function
-delete_old_image_func () {
+# Save image to db function
+save_image_to_list_db_func () {
+	# Exist image to db
+	TEST_EXIST=`echo "$IMAGE" | awk -F ':' 'NF--' | sed "s/ /:/g"`
+	TEST_EXIST=`cat $SAM_DB_LIST | grep $TEST_EXIST`;
+	if [[ -n $TEST_EXIST ]];then
+                echo -e "\E[31mERROR: Image installed to db. ">&2;tput sgr0;
+		echo "List exist images: ./sam -l"
+		echo;
+                exit 1;
+        fi;
+        echo  "Save image to db.";
+	# Collecting info to image
+        IMAGE_ID=`$DOCKER_PATH images | grep -v 'REPOSITORY' | awk -F ' ' ' {print $1,$2,$3} ' | sed "s/ /:/g" | grep "$IMAGE" | awk -F ':' '{print $NF}'`
+        IMAGE_VERSION=`$DOCKER_PATH images | grep -v 'REPOSITORY' | awk -F ' ' ' {print $1,$2} ' | sed "s/ /:/g" | grep "$IMAGE" | awk -F ':' '{print $NF}'`
+        IMAGE_NAME=`$DOCKER_PATH images | grep "$IMAGE_ID" | tail -1 | awk -F ' ' ' {print $1} '`;
+        
+	# Edit db
+	echo -e "$IMAGE_ID\t$IMAGE_NAME\t$IMAGE_VERSION" >> $SAM_DB_LIST;
+}
 
-	# input: $IMAGE $DOCKER_PATH
-	# Image latest?
-	OLD_IMAGE=`$DOCKER_PATH images |grep latest |awk ' {print $1} '| grep $IMAGE`;
-	if [[ -n $OLD_IMAGE ]];then
-		OLD_IMAGE="$IMAGE:latest"
-	else
-		# Image is exists?
-		OLD_IMAGE=`$DOCKER_PATH images |  awk ' {print $1,$2} ' | sed "s/ /:/g" | grep "$IMAGE" `	
-	fi;	
-	
-	if [[ -z $OLD_IMAGE ]]; then
-		echo "No deleted old image. Image $IMAGE is not found. ";
-	else
-		read -p "In system installed old version of image. Uninstall old image? (y/n)" choice
-		case "$choice" in 
-		    y|Y ) uninstall_image_func;
-			  $DOCKER_PATH rmi -f $IMAGE;;
-		    n|N ) echo ;;
-        	    * ) echo "Incorrect input.";
-		        exit 1;;
-        	esac
-	fi;
-	# output:
+# Delete image to db function
+delete_image_to_list_db_func () {
+        echo  "Delete image to db.";
+
+        # Edit db
+        #set -i "/$IMAGE/d" $SAM_DB_LIST;
+	TFILE=`mktemp`;
+	cat $SAM_DB_LIST | grep -v "$IMAGE" > $TFILE;
+	mv $TFILE $SAM_DB_LIST;
+	unset TFILE;
 }
 
 # Image latest?
 image_latest_func (){
-	OLD_IMAGE=`$DOCKER_PATH images |grep latest |awk ' {print $1} '| grep $IMAGE`;
-	if [[ -n $OLD_IMAGE ]];then
+	VERSION_IMAGE=`echo "$IMAGE" | awk -F '/' '{print $NF}' | awk -F ':' '{print $2}'`;
+	if [[ -z $VERSION_IMAGE ]];then
                 IMAGE="$IMAGE:latest"
-        fi;
-	# Exist image
-	TEST_IMAGE=`docker images | grep -v "REPOSITORY" | awk ' {print $1,$2} ' | sed "s/ /:/g" | grep "^$IMAGE"`;
-        if [[ -z $TEST_IMAGE ]]; then
-                echo -e "\E[31mERROR: Not found image $IMAGE.">&2;tput sgr0;
-                echo "Run 'COMMAND -h' for more information on a command.";
-                exit 1;
         fi;
 }
 
@@ -109,21 +101,45 @@ if [[ $EUID -ne 0 ]]; then
     exit 1
 fi
 
+# Exist db?
+if ! [[ -f $SAM_DB_LIST ]];then
+        echo;
+        echo "Not found db sam: $SAM_DB_LIST. Create list."
+        echo;
+        mkdir -p `echo $SAM_DB_LIST | awk -F '/' 'NF--' | sed 's/ /\//g'`;
+        touch $SAM_DB_LIST;
+fi;
+
 USAGE="
 Options:
 	-f  [archive.tar]	Docker load image from tar archive.
 	-i  [image]:[version]	Install selected docker image.
-	-u  [container]		Uninstall selected container.
+	-u  [image]:[version]	Uninstall selected container to db.
 	-x  [-f:-i:-u] 		Debug mode from options.
 	-I  [image]:[version]	Info to image.
+	-l  			List installed image to db.
 	-h           		Help.
+
+Env:
+	DOCKER_PATH		Path docker. default: DOCKER_PATH=$DOCKER_PATH
+	SAM_DB_LIST		Database from installed images. default: SAM_DB_LIST=$SAM_DB_LIST
+	
 ";
 
-while getopts "xi:xf:xu:f:i:u:I:h" OPTION
+while getopts "li:f:u:xI:h" OPTION
 do
     case $OPTION in
+
+	l ) echo "List images:";
+            echo;
+            cat $SAM_DB_LIST | awk -F '\t' 'BEGIN {OFS = ":"} {print $2, $3}';
+            echo;
+	    exit 0
+          ;;
+
 	x ) set -vx
 	  ;;
+
         f ) if [ -f $OPTARG ]; then
 
                 ## Find image name to archive.
@@ -143,40 +159,71 @@ do
 		    exit 1;
 		fi;
 		rm -f repositories;
-		##
-		# Delete old image
-		delete_old_image_func;
-		# Load image
-		$DOCKER_PATH load -i $OPTARG
-		if [[ $? -ne 0 ]]; then	
-		    echo -e "\E[31mERROR: Loading image.">&2;tput sgr0;
-		    exit 1;
-		fi;
-		# Install image
-		install_image_func;
-		echo -e "\E[32mImage installed.";tput sgr0;
+		##`
+		TEST_IMAGE=`cat $SAM_DB_LIST | awk -F '\t' ' {print $2,$3} ' | sed "s/ /:/g" | grep "$IMAGE"`;
+           	if [[ -z $TEST_IMAGE ]];then
+                	echo "Image not found to db."
+			# Load image
+			echo "Loading image $IMAGE."
+			$DOCKER_PATH load -i $OPTARG
+			if [[ $? -ne 0 ]]; then	
+			    echo -e "\E[31mERROR: Loading image.">&2;tput sgr0;
+			    exit 1;
+			fi;
+			# Install image
+			save_image_to_list_db_func;
+			install_image_func;
+			echo -e "\E[32mImage installed.";tput sgr0;
+		else 
+			echo -e "\E[31mERROR: Image exist to db.">&2;tput sgr0;
+			exit 1;
+	   	fi;
 	   else
 		echo -e "\E[31m$0: Archive image not defined." >&2;tput sgr0;
 		exit 1;
 	   fi
 	  ;;
 
-	i )IMAGE=$OPTARG;
+	i ) IMAGE=$OPTARG;
 	   image_latest_func;
+	   # Installed image?
+	   TEST_IMAGE=`cat $SAM_DB_LIST | awk -F '\t' ' {print $2,$3} ' | sed "s/ /:/g" | grep "$IMAGE"`;
+	   if [[ -n $TEST_IMAGE ]];then
+		echo -e "\E[31mERROR: Image found to db. Stop installation.">&2;tput sgr0;
+		exit 1;
+	   fi;
+	   # Exist image?
+	   TEST_IMAGE=`$DOCKER_PATH images | grep -v 'REPOSITORY' | awk -F ' ' ' {print $1,$2} ' | sed "s/ /:/g" | grep "$IMAGE"`;
+	   if [[ -z $TEST_IMAGE ]];then
+                echo -e "\E[31mERROR: Image not found to registry docker. Stop installation.">&2;tput sgr0;
+                exit 1;
+           fi;
 	   # Install image
+	   save_image_to_list_db_func;
 	   install_image_func;
 	   echo -e "\E[32mImage installed.";tput sgr0;
 	   exit 0
 	  ;;
 	
-	u ) IMAGE=`$DOCKER_PATH ps -a | grep " $OPTARG " | unexpand -a -t2|awk -F '\t+' '{print $2}'`;
-	   if [[ -z $IMAGE ]]; then
-		echo -e "\E[31mERROR: Not found image for container $OPTARG.">&2;tput sgr0;
-		echo "Run 'COMMAND -h' for more information on a command.";
-		exit 1;
-	   fi;
+	u ) IMAGE=$OPTARG;
+           image_latest_func;
+	   # Installed image?
+           TEST_IMAGE=`cat $SAM_DB_LIST | awk -F '\t' ' {print $2,$3} ' | sed "s/ /:/g" | grep "$IMAGE"`;
+           if [[ -z $TEST_IMAGE ]];then
+                echo -e "\E[31mERROR: Image not found to db.">&2;tput sgr0;
+                exit 1;
+	   else
+		IMAGE=`$DOCKER_PATH images | grep -v 'REPOSITORY' | awk -F ' ' ' {print $1,$2,$3} ' | sed "s/ /:/g" | grep "$IMAGE" | awk -F ':' '{print $NF}'`
+           fi;
+           # Exist image?  
+           TEST_IMAGE=`$DOCKER_PATH images | grep -v 'REPOSITORY' | awk -F ' ' ' {print $3} ' | grep "$IMAGE"`;
+           if [[ -z $TEST_IMAGE ]];then
+                echo -e "\E[31mERROR: Image not found to registry docker.">&2;tput sgr0;
+                exit 1;
+           fi;
 	   # Uninstall image
 	   uninstall_image_func;
+	   delete_image_to_list_db_func;
            echo -e "\E[32mImage uninstalled.";tput sgr0;
            exit 0
 	  ;;
@@ -198,19 +245,26 @@ do
 	  ;;
 
         h ) echo "$USAGE"; 
-	    exit
+	    exit 0
           ;;
+
         *) echo
 	  ;;
     esac
 done
 
-if [[ -z $IMAGE ]]; then 
+if [[ -z $IMAGE ]];then 
 	IMAGE=$1;
+	image_latest_func;
+	TEST_IMAGE=`cat $SAM_DB_LIST | awk -F '\t' ' {print $2,$3} ' | sed "s/ /:/g" | grep "$IMAGE"`;
+        if [[ -n $TEST_IMAGE ]];then
+            echo -e "\E[31mERROR: Image found to db. Stop installation.">&2;tput sgr0;
+            exit 1;
+        fi;
 	# Pull
 	$DOCKER_PATH pull $IMAGE;
 	if [[ $? -eq 0 ]]; then
-		image_latest_func;
+		save_image_to_list_db_func;
 		install_image_func;
 		echo -e "\E[32mImage installed.";tput sgr0;
 	else
@@ -218,5 +272,3 @@ if [[ -z $IMAGE ]]; then
 		exit 1;
 	fi;
 fi;
-
-
