Corrected install image. Added error message.

diff --git a/sam b/sam
--- a/sam
+++ b/sam
@@ -10,7 +10,7 @@ IMAGE='';
 copy_meta_func () {
 	# input: $IMAGE $DOCKER_PATH
 	TEMPLATE_DIR=`mktemp -d`;
-	$DOCKER_PATH run -i -t --rm=true -v $TEMPLATE_DIR:$TEMPLATE_DIR  --net=host $IMAGE /bin/sh -c "cp -r /meta $TEMPLATE_DIR/meta" 2>&1 > /dev/null;
+	$DOCKER_PATH run -i -t --rm -v $TEMPLATE_DIR:$TEMPLATE_DIR  --net=host --entrypoint="cp"  $IMAGE -r /meta $TEMPLATE_DIR/meta 2>&1 > /dev/null;
 	if [[ $? -ne 0 ]]; then
         	echo -e "\E[31mERROR: Directory '/meta' not fount to image.">&2;tput sgr0;
 		rm -rf $TEMPLATE_DIR
@@ -21,8 +21,8 @@ copy_meta_func () {
 
 # Uninstall image function
 uninstall_image_func () {
-	echo;
-	echo -e "\E[32mUninstall image $IMAGE";tput sgr0;
+	echo;	
+	echo -e "\E[32mUninstall image $IMAGE.";tput sgr0;
 	copy_meta_func;
 	pwd=$PWD;
 	cd $TEMPLATE_DIR/meta;
@@ -36,16 +36,19 @@ uninstall_image_func () {
 install_image_func () {
 	echo;
 	echo -e "\E[32mInstall image $IMAGE";tput sgr0;
-	TEST_CONTAINER=`docker ps -a | grep $IMAGE`;
+	# Exist installed image
+	OLD_IMAGE=`echo $IMAGE | awk -F ':' 'NF--' | sed 's/ /:/g'`
+	TEST_CONTAINER=`$DOCKER_PATH ps -a | grep $OLD_IMAGE`;	
 	if [[ -n $TEST_CONTAINER ]]; then
-		read -p "In system already stared container. Uninstall image? (y/n)" choice
-		case "$choice" in
-                    y|Y ) uninstall_image_func;;
-                    n|N ) exit 0;;
-                    * ) echo "Incorrect input.";
-                        exit 1;;
-                esac
+		echo -e "\E[31mERROR: In system installed old version of image..">&2;tput sgr0;
+		echo;
+		echo "    Installed image:";
+		echo;
+	        $DOCKER_PATH ps -a | grep --color=always $OLD_IMAGE;
+		echo;
+		exit 1;
 	fi;
+	
 	copy_meta_func;
 	pwd=$PWD;
         cd $TEMPLATE_DIR/meta;
@@ -53,7 +56,7 @@ install_image_func () {
 	source $TEMPLATE_DIR/meta/install;
 	cd $pwd;
 	rm -rf $TEMPLATE_DIR;
-	echo;
+	echo;	
 }
 
 # Remove old image function
@@ -166,7 +169,7 @@ do
 	   exit 0
 	  ;;
 	
-	u ) IMAGE=`$DOCKER_PATH ps -a | grep $OPTARG | unexpand -a -t2|awk -F '\t+' '{print $2}'`;
+	u ) IMAGE=`$DOCKER_PATH ps -a | grep " $OPTARG " | unexpand -a -t2|awk -F '\t+' '{print $2}'`;
 	   if [[ -z $IMAGE ]]; then
 		echo -e "\E[31mERROR: Not found image for container $OPTARG.">&2;tput sgr0;
 		echo "Run 'COMMAND -h' for more information on a command.";
